version: "3"

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: imersao-fullcycle-3-store-frontend-app
    restart: unless-stopped
    ports:
      - 3060:3060
    volumes:
      - .:/home/node/app
    extra_hosts: 
      - 'host.docker.internal:172.17.0.1'
